{% set name = "celerite" %}
{% set version = "0.1.3" %}
{% set sha256 = "abf9ab06df52ecb442a3ed46477a7751590399d9247ea0c42d1af9dee71b1cb4" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../.

build:
  number: 0
  script:
    - LAPACK_VARIANT='blas_opt' python setup.py install --single-version-externally-managed --record record.txt  # [not win]
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - eigen
    - pybind11
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - numpy >=1.11
  run:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - numpy >=1.11
    - setuptools  # [win]
    - vs2015_runtime  # [win]

test:
  imports:
    - celerite

about:
  home: http://github.com/dfm/celerite
  license: MIT
  summary: 'Scalable 1D Gaussian Processes in C++ and Python'
  doc_url: http://celerite.readthedocs.io/
  dev_url: https://github.com/dfm/celerite

extra:
  recipe-maintainers:
    - dfm
